"use server";

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
import { logger } from "@/lib/logger";
import {
  createCerereSchema,
  updateCerereSchema,
  CerereStatus,
  canModifyCerere,
  type CerereStatusType,
} from "@/lib/validations/cereri";
import { validateRequiredDocuments } from "@/lib/cereri/document-validation";
import { sendCerereSubmittedSMS } from "@/lib/sms";
import type { Json } from "@/types/database.types";

/**
 * Result type for createDraft action.
 */
interface CreateDraftResult {
  success: boolean;
  data?: { id: string };
  error?: string;
}

/**
 * Result type for updateDraft action.
 */
interface UpdateDraftResult {
  success: boolean;
  error?: string;
}

/**
 * Result type for deleteDraft action.
 */
interface DeleteDraftResult {
  success: boolean;
  error?: string;
}

/**
 * Result type for submitDraft action.
 */
interface SubmitDraftResult {
  success: boolean;
  data?: { numar_inregistrare: string };
  error?: string;
}

/**
 * Create a new cerere draft.
 *
 * Equivalent to POST /api/cereri.
 * Uses createClient() from server.ts which inherits x-primarie-id
 * from the page request context (set by middleware on /app/* paths).
 *
 * @param tipCerereId - UUID of the request type
 * @param formData - Dynamic form data
 * @param observatii - Optional additional notes from the applicant
 * @returns CreateDraftResult with the new cerere ID or error
 */
export async function createDraft(
  tipCerereId: string,
  formData: Record<string, unknown>,
  observatii?: string
): Promise<CreateDraftResult> {
  try {
    const supabase = await createClient();

    // Check authentication
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return { success: false, error: "Autentificare necesara" };
    }

    // Validate input
    const parseResult = createCerereSchema.safeParse({
      tip_cerere_id: tipCerereId,
      date_formular: formData,
      observatii_solicitant: observatii,
    });

    if (!parseResult.success) {
      return {
        success: false,
        error: parseResult.error.issues[0]?.message || "Date invalide",
      };
    }

    const validatedData = parseResult.data;

    // Get user's primarie_id from utilizatori table
    const { data: utilizator, error: utilizatorError } = await supabase
      .from("utilizatori")
      .select("primarie_id")
      .eq("id", user.id)
      .single();

    if (utilizatorError || !utilizator) {
      return {
        success: false,
        error: "Utilizator negasit. Va rugam sa selectati judetul si localitatea.",
      };
    }

    // Verify tip_cerere exists and is active
    const { data: tipCerere, error: tipCerereError } = await supabase
      .from("tipuri_cereri")
      .select("id, necesita_taxa, valoare_taxa, termen_legal_zile")
      .eq("id", validatedData.tip_cerere_id)
      .eq("activ", true)
      .single();

    if (tipCerereError || !tipCerere) {
      return {
        success: false,
        error: "Tipul de cerere nu exista sau nu este activ",
      };
    }

    // Calculate data_termen if termen_legal_zile is set
    const dataTermen = tipCerere.termen_legal_zile
      ? new Date(Date.now() + tipCerere.termen_legal_zile * 24 * 60 * 60 * 1000).toISOString()
      : null;

    // Create cerere
    // Note: numar_inregistrare is auto-generated by trigger - omit field to let trigger handle it
    const insertData = {
      primarie_id: utilizator.primarie_id,
      tip_cerere_id: validatedData.tip_cerere_id,
      solicitant_id: user.id,
      date_formular: validatedData.date_formular as unknown as Json,
      observatii_solicitant: validatedData.observatii_solicitant || null,
      status: CerereStatus.DEPUSA,
      necesita_plata: tipCerere.necesita_taxa,
      valoare_plata: tipCerere.valoare_taxa,
      data_termen: dataTermen,
    };

    // Type assertion needed: trigger auto-generates numar_inregistrare,
    // but TypeScript types don't know about DB triggers
    const { data: cerere, error: insertError } = await supabase
      .from("cereri")
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .insert(insertData as any)
      .select("id")
      .single();

    if (insertError) {
      logger.error("Database error creating cerere draft:", insertError);
      return { success: false, error: "Eroare la crearea cererii" };
    }

    revalidatePath("/app");
    return { success: true, data: { id: cerere.id } };
  } catch (error) {
    logger.error("Unexpected error in createDraft:", error);
    return { success: false, error: "A aparut o eroare neasteptata" };
  }
}

/**
 * Update an existing cerere draft.
 *
 * Equivalent to PATCH /api/cereri/[id].
 * Validates ownership, checks status allows modification, then updates.
 *
 * @param draftId - The cerere UUID to update
 * @param formData - Updated dynamic form data
 * @param observatii - Optional updated notes from the applicant
 * @returns UpdateDraftResult with success/error
 */
export async function updateDraft(
  draftId: string,
  formData: Record<string, unknown>,
  observatii?: string
): Promise<UpdateDraftResult> {
  try {
    const supabase = await createClient();

    // Check authentication
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return { success: false, error: "Autentificare necesara" };
    }

    // Validate input
    const parseResult = updateCerereSchema.safeParse({
      date_formular: formData,
      observatii_solicitant: observatii,
    });

    if (!parseResult.success) {
      return {
        success: false,
        error: parseResult.error.issues[0]?.message || "Date invalide",
      };
    }

    const validatedData = parseResult.data;

    // Check if cerere exists and belongs to user
    const { data: existingCerere, error: fetchError } = await supabase
      .from("cereri")
      .select("id, status, solicitant_id")
      .eq("id", draftId)
      .is("deleted_at", null)
      .single();

    if (fetchError || !existingCerere) {
      return { success: false, error: "Cererea nu a fost gasita" };
    }

    // Verify ownership
    if (existingCerere.solicitant_id !== user.id) {
      return { success: false, error: "Nu aveti permisiunea de a modifica aceasta cerere" };
    }

    // Check if cerere can be modified based on status
    if (!canModifyCerere(existingCerere.status as CerereStatusType)) {
      return { success: false, error: "Cererea nu poate fi modificata in starea curenta" };
    }

    // Build update object (only include provided fields)
    const updateData: Record<string, unknown> = {
      updated_at: new Date().toISOString(),
    };

    if (validatedData.date_formular !== undefined) {
      updateData.date_formular = validatedData.date_formular;
    }

    if (validatedData.observatii_solicitant !== undefined) {
      updateData.observatii_solicitant = validatedData.observatii_solicitant;
    }

    // Update cerere
    const { error: updateError } = await supabase
      .from("cereri")
      .update(updateData)
      .eq("id", draftId);

    if (updateError) {
      logger.error("Database error updating cerere draft:", updateError);
      return { success: false, error: "Eroare la actualizarea cererii" };
    }

    revalidatePath("/app");
    return { success: true };
  } catch (error) {
    logger.error("Unexpected error in updateDraft:", error);
    return { success: false, error: "A aparut o eroare neasteptata" };
  }
}

/**
 * Delete (soft-delete) a cerere draft.
 *
 * Equivalent to DELETE /api/cereri/[id].
 * Only drafts in 'depusa' status can be deleted.
 *
 * @param draftId - The cerere UUID to delete
 * @returns DeleteDraftResult with success/error
 */
export async function deleteDraft(draftId: string): Promise<DeleteDraftResult> {
  try {
    const supabase = await createClient();

    // Check authentication
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return { success: false, error: "Autentificare necesara" };
    }

    // Check if cerere exists and belongs to user
    const { data: existingCerere, error: fetchError } = await supabase
      .from("cereri")
      .select("id, status, solicitant_id")
      .eq("id", draftId)
      .is("deleted_at", null)
      .single();

    if (fetchError || !existingCerere) {
      return { success: false, error: "Cererea nu a fost gasita" };
    }

    // Verify ownership
    if (existingCerere.solicitant_id !== user.id) {
      return { success: false, error: "Nu aveti permisiunea de a sterge aceasta cerere" };
    }

    // Only allow deleting drafts (depusa status)
    if (existingCerere.status !== CerereStatus.DEPUSA) {
      return { success: false, error: "Doar cererile in status 'depusa' pot fi sterse" };
    }

    // Soft delete by setting deleted_at timestamp
    const { error: deleteError } = await supabase
      .from("cereri")
      .update({ deleted_at: new Date().toISOString() })
      .eq("id", draftId);

    if (deleteError) {
      logger.error("Database error deleting cerere draft:", deleteError);
      return { success: false, error: "Eroare la stergerea cererii" };
    }

    revalidatePath("/app");
    return { success: true };
  } catch (error) {
    logger.error("Unexpected error in deleteDraft:", error);
    return { success: false, error: "A aparut o eroare neasteptata" };
  }
}

/**
 * Submit a cerere draft for processing.
 *
 * Equivalent to POST /api/cereri/[id]/submit.
 * Transitions cerere from 'depusa' to 'in_verificare' status.
 * Validates required documents are uploaded before submission.
 * Sends SMS notification if user has SMS enabled.
 *
 * @param draftId - The cerere UUID to submit
 * @returns SubmitDraftResult with numar_inregistrare or error
 */
export async function submitDraft(draftId: string): Promise<SubmitDraftResult> {
  try {
    const supabase = await createClient();

    // Check authentication
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();

    if (authError || !user) {
      return { success: false, error: "Autentificare necesara" };
    }

    // Check if cerere exists and belongs to user
    const { data: existingCerere, error: fetchError } = await supabase
      .from("cereri")
      .select("id, status, solicitant_id, tip_cerere_id")
      .eq("id", draftId)
      .is("deleted_at", null)
      .single();

    if (fetchError || !existingCerere) {
      return { success: false, error: "Cererea nu a fost gasita" };
    }

    // Verify ownership
    if (existingCerere.solicitant_id !== user.id) {
      return { success: false, error: "Nu aveti permisiunea de a trimite aceasta cerere" };
    }

    // Check if cerere is in correct status for submission
    if (existingCerere.status !== CerereStatus.DEPUSA) {
      return { success: false, error: "Cererea nu poate fi trimisa in starea curenta" };
    }

    // Validate that required documents are uploaded
    const docValidation = await validateRequiredDocuments(
      supabase,
      draftId,
      existingCerere.tip_cerere_id!
    );
    if (!docValidation.valid) {
      return {
        success: false,
        error: `Lipsesc documente obligatorii: ${docValidation.missing.join(", ")}`,
      };
    }

    // Update cerere status to in_verificare
    const { data: updatedCerere, error: updateError } = await supabase
      .from("cereri")
      .update({
        status: CerereStatus.IN_VERIFICARE,
        updated_at: new Date().toISOString(),
      })
      .eq("id", draftId)
      .select("id, numar_inregistrare")
      .single();

    if (updateError) {
      logger.error("Database error submitting cerere:", updateError);
      return { success: false, error: "Eroare la trimiterea cererii" };
    }

    // Send SMS notification to user if enabled
    try {
      const { data: utilizator } = await supabase
        .from("utilizatori")
        .select("telefon, sms_notifications_enabled")
        .eq("id", user.id)
        .single();

      if (utilizator?.sms_notifications_enabled && utilizator?.telefon) {
        const smsResult = await sendCerereSubmittedSMS(
          utilizator.telefon,
          updatedCerere.id,
          user.id
        );

        if (!smsResult.success) {
          logger.error("Failed to send cerere submitted SMS:", smsResult.error);
          // Don't fail the request - cerere was submitted successfully
        } else {
          logger.debug(`SMS sent to ${utilizator.telefon} for cerere ${updatedCerere.id}`);
        }
      }
    } catch (smsError) {
      logger.error("Error sending cerere submitted SMS:", smsError);
      // Don't fail the request - cerere was submitted successfully
    }

    revalidatePath("/app");
    return {
      success: true,
      data: { numar_inregistrare: updatedCerere.numar_inregistrare },
    };
  } catch (error) {
    logger.error("Unexpected error in submitDraft:", error);
    return { success: false, error: "A aparut o eroare neasteptata" };
  }
}
