theme: jekyll-theme-cayman
title: "primariaTa❤️_ - Documentație"
description: "Platformă SaaS white-label pentru digitalizarea primăriilor din România"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

baseurl: "/primariata.work"
url: "https://mihaigoctavian24.github.io"

# IMPORTANT: Include README.md processing
include:
  - README.md
  - _*

exclude:
  - .gitkeep
  - node_modules/
  - vendor/
